- src/classes/VOL_CTRL_VolunteersSignup.cls
- src/classes/VOL_CTRL_VolunteersSignup_TEST.cls
- src/labels/CustomLabels.labels
super low hanging fruit of fixing this label name.
> change label value, as noted in #122

- src/classes/VOL_CTRL_PersonalSiteContactInfo.cls
- src/classes/VOL_CTRL_VolunteersJobListingFS.cls
This closes #142  and I'm bad at tagging issues in github.
> Namespace Prefix Helper to close #142

- src/classes/VOL_CTRL_VolunteersJobListingFS.cls
> UPDATE User Friendly Validation Rule Error Msg

- src/classes/VOL_CTRL_VolunteersReportHours.cls
- src/objects/Volunteer_Hours__c.object
- src/pages/VolunteersReportHours.page
Allows the user to add comments when entering hours on the personal site. The comments field is available through the VolunteersReportHoursFS fieldset on the volunteers hours object.
> Add comments field on personal site when entering hours.

- src/classes/VOL_CTRL_VolunteersReportHours.cls
- src/classes/VOL_SharedCode.cls
- src/labels/CustomLabels.labels
- src/objects/Volunteers_Settings__c.object
- src/pages/VolunteersReportHours.page
Hi David,
This is the last enhancement to the package, allowing the jobs dropdown on the personal site report hours to be filtered by contact.
Thanks. Vladimir
> volunteer personal hours page - filter jobs by contact

- src/classes/VOL_CTRL_SendBulkEmail.cls
- src/objects/Campaign.object
- src/objects/Volunteer_Job__c.object
- src/objects/Volunteer_Shift__c.object
- The Mass Email Volunteers button now works correctly under Lightning Experience.
> fix Mass Email Volunteers buttons to work under LEX

- src/classes/UTIL_PageMessages_CTRL.cls
- src/classes/UTIL_PageMessages_CTRL.cls-meta.xml
- src/classes/VOL_CTRL_VolunteersBulkEnterHours.cls
- src/classes/VOL_CTRL_VolunteersBulkEnterHours_TEST.cls
- src/components/UTIL_NavigateBack.component
- src/components/UTIL_NavigateBack.component-meta.xml
- src/components/UTIL_PageMessages.component
- src/components/UTIL_PageMessages.component-meta.xml
- src/labels/CustomLabels.labels
- src/package.xml
- src/pages/VolunteersBulkEnterHours.page
- src/staticresources/sfdo213.resource-meta.xml
- src/staticresources/v4s_slds.resource
- src/staticresources/v4s_slds.resource-meta.xml
- src/translations/de.translation
- src/translations/en_US.translation
- src/translations/es.translation
- src/translations/fr.translation
- src/translations/ja.translation
- The Mass Enter Volunteer Hours page has now been updated to use Lightning styling to provide consistency with Lightning Experience.
> SLDS'ing of Mass Enter Volunteer Hours, and shared util components

- src/pages/NewAndEditVRS.page
> Removing html validation to fix cancel

- circle.yml
- cumulusci.yml
- orgs/beta.json
- orgs/dev.json
- orgs/feature.json
- orgs/release.json
- workspace-config.json
This only changes the build configuration and does not touch any package code.
> Configure for CumulusCI 2 w/ scratch orgs and CircleCI

- cumulusci.yml
> Add ci_browsertests that installs the beta but doesn't run apex tests

- src/applications/Groundwire_Volunteers.app
- src/classes/VOL_VRS.cls
- src/classes/VOL_VRS_TEST.cls
> Make contacts with multiple VRS's to same Job work correctly. Issue #230

- src/classes/VOL_CTRL_NewAndEditVRS_TEST.cls
- src/classes/VOL_VRS_TEST.cls
- src/pages/VolunteersBulkEnterHours.page
> test fixes

- src/objectTranslations/Contact-ja.objectTranslation
- src/objectTranslations/Lead-ja.objectTranslation
- src/objectTranslations/Volunteer_Job__c-ja.objectTranslation
- src/objectTranslations/Volunteers_Settings__c-ja.objectTranslation
- src/translations/ja.translation
This PR includes the calendar label fixes from the other PR - I wasn't sure if not including it would cause you a merge conflict.
- Updates to Japanese translations.
> Updates to Japanese translations

- src/objectTranslations/Job_Recurrence_Schedule__c-fr.objectTranslation
- src/objectTranslations/Volunteer_Job__c-fr.objectTranslation
- src/objectTranslations/Volunteer_Recurrence_Schedule__c-fr.objectTranslation
- src/objectTranslations/Volunteers_Settings__c-fr.objectTranslation
- src/translations/fr.translation
- Updates to French translations.
> Includes french translation updates

- src/objectTranslations/Volunteer_Job__c-de.objectTranslation
- src/objectTranslations/Volunteers_Settings__c-de.objectTranslation
- src/translations/de.translation
This one also includes the calendar format label fixes for German.
- Updates to German translations.
> Updating German translations

- cumulusci.yml
> update cumulusci.yml to run browser tests in mrbelvedereci

- src/pages/JobCalendar.page
turns out a JSENCODE Joy and I added was incorrect.  I removed the JSENCODE and tested descriptions with special characters and they are correctly handled by the FullCalendar component.  Using JSENCODE or javascript's escape() on the string actually causes problems!
> JSENCODE fix

- .gitIgnore
- cumulusci.properties
- cumulusci.yml
- dev_config/delete/destructiveChanges.xml
- dev_config/delete/package.xml
- dev_config/src/package.xml
- dev_config/src/profiles/Admin.profile
- sfdx-project.json
> Scratch org dev_config

- src/pages/VolunteersJobListingFS.page
- This release fixes the popup signup dialog that was not working in the Firefox browser.
Fixed #313
> remove dialog positioning code that broke in latest JQueryUI. 

- src/classes/VOL_CTRL_JobCalendar.cls
- src/labels/CustomLabels.labels
- src/pages/JobCalendar.page
> Add FLS error message to Job Calendar

- src/pages/VolunteersFind.page
> added id to status field

- src/pages/VolunteersJobListingFS.page
> VolunteersJobListingFS page Sign Up link for Job Issue

- cumulusci.yml
- src/package.xml
> Update dev flow for cci 2, and pin api_version

- src/classes/VOL_CTRL_SendBulkEmail.cls
- src/classes/VOL_CTRL_SendBulkEmail_TEST.cls
- src/pages/PersonalSiteTemplateEspanol.page-meta.xml
- src/pages/SendBulkEmail.page
> Prevent xss in html from email template

- src/classes/VOL_CTRL_SendBulkEmail.cls
> Update comment for additional details around work around.

- push/orgs_qa.txt
> Update the NGO QA sandbox org id

- .gitIgnore
- src/classes/VOL_CTRL_JobCalendar.cls
- src/pages/JobCalendar.page
- src/pages/VolunteersAbout.page
> Preventing xss in job calendar

- src/pages/PersonalSiteContactLookup.page
NOTE: Converted tabs to spaces and applied SFDX plugin auto formatting in the first commit so the actual changes can be easier seen in the second commit.
- Fixes #373
> Fix Personal Site Contact Labels XSS Vulnerability

- src/classes/UTIL_JavaScriptSanitizer.cls
- src/classes/UTIL_JavaScriptSanitizer.cls-meta.xml
- src/classes/UTIL_JavaScriptSanitizer_TEST.cls
- src/classes/UTIL_JavaScriptSanitizer_TEST.cls-meta.xml
- src/classes/VOL_CTRL_JobCalendar.cls
- src/classes/VOL_CTRL_JobCalendar_TEST.cls
- src/package.xml
- src/pages/JobCalendar.page
Security Issues addressed on JobCalendar page.
Fixes XSS issues on JobCalendar due to custom labels used in JavaScript
> Fix for XSS issues on JobCalendar VF page

- src/classes/VOL_CTRL_VolunteersJobListingFS.cls
- src/layouts/Volunteer_Job__c-Volunteer Job Layout.layout
- src/objects/Volunteer_Job__c.object
- src/package.xml
- src/pages/VolunteersJobListingFS.page
> Reverts changes related to adding ExternalSignupLink__c

- src/workflows/Volunteer_Hours__c.workflow
> Implement bug workaround. Change TODAY criteria to formula Today()

- src/classes/InstallScript.cls
// Grasping at straws, but thinking maybe previous version when going from managed to beta is causing an issue?
> Install script now checking for upgrade vs new

- src/classes/InstallScript.cls
- src/classes/Telemetry.cls
- src/classes/Telemetry_TEST.cls
> Move query to future method

- src/classes/InstallScript.cls
> Email Install Error

- src/classes/InstallScript.cls
> Change error email address

- src/classes/QueryBuilder.cls
> Query builder inherits sharing

- src/classes/TelemetryService.cls
- src/classes/TelemetryService_TEST.cls
> Call single feature param direct in future

- src/classes/TelemetryService.cls
- src/classes/TelemetryService_TEST.cls
> Remove send test

- src/classes/InstallScript.cls
- src/classes/Telemetry.cls
- src/classes/TelemetryService.cls
- src/classes/Telemetry_TEST.cls
> Fix missing criteria and catch email errors

- dev_config/src/permissionsets/V4S_Site_Minimum.permissionset
- src/classes/QueryBuilder.cls
- src/classes/QueryBuilder_TEST.cls
- src/classes/VOL_CTRL_VolunteersJobListingFS.cls
- src/classes/VOL_CTRL_VolunteersJobListingFS_TEST.cls
> Display jobs with hundreds of shifts

- src/classes/VOL_CTRL_VolunteersJobListingFS.cls
> Add namespace prefix to child relationship name.

- dev_config/src/permissionsets/V4S_Site_Minimum.permissionset
- src/classes/QueryBuilder.cls
- src/classes/QueryBuilder_TEST.cls
- src/classes/VOL_CTRL_VolunteersJobListingFS.cls
- src/classes/VOL_CTRL_VolunteersJobListingFS_TEST.cls
- src/classes/VOL_CTRL_VolunteersReportHours.cls
- src/classes/VOL_SharedCode.cls
> Undo changes to job listing to fix exposure of unlisted shifts

- src/pages/VolunteersBulkEnterHours.page
- Fixes: [#271](https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/issues/271#issuecomment-287424957)
> Disable Mass Hour Update Buttons During Save

- src/classes/VOL_VRS.cls
- src/classes/VOL_VRS_TEST.cls
// This is the internal branch used to run Nic's Pull Request through our build system.
Shifts that are on the same day but don't overlap are no longer being incorrectly reparented. 
- Fixes #377
> Avoid reparenting hours from one VRS to another

- LICENSE
> Updated V4S License

- orgs/beta.json
- orgs/dev.json
- orgs/feature.json
- orgs/prerelease.json
- orgs/release.json
This PR updates V4S's org definition files to use the new orgPreferenceSettings format, required in Winter '20.
> Update org definitions to use orgPreferenceSettings

- .gitignore
> Ignore .cci

- datasets/regression/test_data.sql
> Uniquify the emails in regression data set

- datasets/regression/test_data.sql
> Add Jobs without Shifts to data set

- src/classes/DatabaseDml.cls
- src/classes/DatabaseDml_TEST.cls
- src/classes/UTIL_Describe.cls
- src/classes/UTIL_Describe_TEST.cls
- src/classes/UTIL_UnitTest.cls
- src/classes/VOL_Access.cls
- src/classes/VOL_Access.cls-meta.xml
- src/classes/VOL_Access_TEST.cls
- src/classes/VOL_Access_TEST.cls-meta.xml
- src/classes/VOL_SharedCode.cls
- src/classes/VOL_SharedCode_TEST.cls
- src/package.xml
> Move guest access check to Access class

- src/classes/VOL_Access_TEST.cls
- src/classes/VOL_CTRL_VolunteersJobListingFS.cls
- src/classes/VOL_CTRL_VolunteersJobListingFS_TEST.cls
> Use new access wrapper for job listing signups

- src/classes/UTIL_UnitTest.cls
- src/classes/VOL_Access_TEST.cls
- src/classes/VOL_CTRL_VolunteersReportHours.cls
- src/classes/VOL_CTRL_VolunteersReportHours_TEST.cls
> Use Access Wrapper on Report Hours Page

- src/classes/UTIL_UnitTest.cls
- src/classes/VOL_Access.cls
- src/classes/VOL_CTRL_PersonalSiteContactInfo_TEST.cls
- src/classes/VOL_CTRL_PersonalSiteContactLookup_TEST.cls
- src/classes/VOL_CTRL_VolunteersJobListingFS_TEST.cls
- src/classes/VOL_CTRL_VolunteersJobListing_TEST.cls
- src/classes/VOL_CTRL_VolunteersReportHours_TEST.cls
- src/classes/VOL_CTRL_VolunteersSignupFS_TEST.cls
- src/classes/VOL_CTRL_VolunteersSignup_TEST.cls
- src/classes/VOL_SharedCode.cls
- src/objects/Volunteers_Settings__c.object
- src/package.xml
> Add guest access custom setting

- orgs/beta_prerelease.json
- orgs/prerelease.json
> Add beta prerelease build

- src/classes/VOL_CTRL_VolunteersJobListing.cls
- src/classes/VOL_CTRL_VolunteersJobListing_TEST.cls
- src/classes/VOL_SharedCode.cls
- src/classes/VOL_SharedCode_TEST.cls
> Use access wrapper on job listing w/out fieldset

- src/classes/UTIL_UnitTest.cls
- src/classes/VOL_Access_TEST.cls
- src/classes/VOL_CTRL_VolunteersReportHours_TEST.cls
- src/classes/VOL_SharedCode.cls
- src/classes/VOL_SharedCode_TEST.cls
- src/classes/VOL_TEST_VolunteerHours_Trigger.cls
// Switched the guest profile to 'Guest License User' since the 'Standard Guest User' does not appear to be included in Dev orgs.
> Use Access Wrapper for Hours Trigger

- src/classes/VOL_CTRL_PersonalSiteContactInfo.cls
- src/classes/VOL_CTRL_PersonalSiteContactInfo_TEST.cls
- src/classes/VOL_SharedCode.cls
- src/classes/VOL_SharedCode_TEST.cls
> Fix contact update access check

- src/classes/Telemetry.cls
- src/classes/TelemetryService.cls
- src/classes/Telemetry_TEST.cls
- src/featureParameters/GrantGuestUsersUpdateAccess.featureParameterBoolean
- src/package.xml
> Add Telemetry for grant users update access boolean value

- src/classes/UTIL_UnitTest.cls
> Find either OOB guest profiles for different orgs

- cumulusci.yml
This PR updates configuration of the V4S MetaDeploy installer.
> Tweak MetaDeploy installation parameters

- cumulusci.yml
- unpackaged/config/npsp_v4s_layouts/layouts/Contact-Volunteers Contact Layout.layout
> Correct minor issues in MetaDeploy installer

- documentation/automation.md
This PR adds basic reference documentation for the project's automation.
> Add automation documentation

- cumulusci.yml
- orgs/beta.json
- orgs/beta_prerelease.json
- orgs/dev.json
- orgs/feature.json
- orgs/prerelease.json
- orgs/release.json
This PR updates the org settings format in all `.json` files. It also turns on parallel Apex test runs with automated retry of row locking errors.
> Activate parallel test retries and update org settings format

- src/pages/PersonalSiteContactInfo.page
- src/pages/PersonalSiteTemplate.page
- src/pages/PersonalSiteTemplateEspanol.page
> Fix reference to package namespace not resolving

- src/classes/VOL_CTRL_PersonalSiteContactInfo.cls
- src/classes/VOL_CTRL_PersonalSiteContactInfo_TEST.cls
> Update lifetime calculation to use count query

- src/package.xml
> V4S Package Update

- src/classes/VOL_SharedCode.cls
> Fix option label on shifts

- datasets/regression/test_data.sql
This PR removes elements of the data set that are less suitable for use outside Salesforce.org.
> Sanitize data for public use

- src/tabs/Volunteer_Shift__c.tab
> Created Volunteer Shift Custom Tab

- src/tabs/Volunteer_Hours__c.tab
> Created Volunteer Hours Tab

- cumulusci.yml
This PR adds the hidden update installer to MetaDeploy.
> Implement Upgrade Installer

- cumulusci.yml
- metadeploy/labels_en.json
> Implement chatter preflight check

- .github/PULL_REQUEST_TEMPLATE.md
- src/classes/DatabaseDml.cls
- src/classes/SoqlListView.cls
- src/classes/VOL_Access.cls
- src/classes/VOL_CTRL_JobCalendar.cls
- src/classes/VOL_CTRL_PersonalSiteContactInfo.cls
- src/classes/VOL_CTRL_PersonalSiteContactLookup.cls
- src/classes/VOL_CTRL_SendBulkEmail.cls
- src/classes/VOL_CTRL_VolunteersBulkEnterHours.cls
- src/classes/VOL_CTRL_VolunteersCampaignWizard.cls
- src/classes/VOL_CTRL_VolunteersFind.cls
- src/classes/VOL_CTRL_VolunteersJobListing.cls
- src/classes/VOL_CTRL_VolunteersJobListingFS.cls
- src/classes/VOL_CTRL_VolunteersReportHours.cls
- src/classes/VOL_SharedCode.cls
- unpackaged/config/dev/package.xml
- unpackaged/config/dev/permissionsets/V4S_Internal_Minimum.permissionset
* Increase CRUD and FLS checks [[PR519](https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/pull/519)]
> 240 to Main

- metadeploy/labels_en.json
- src/pages/VolunteersAbout.page
Updates in-app documentation links
> Remove in-app doc links to powerofus

- cumulusci.yml
Removes the chatter check from install plan
Fixes #525
> Remove chatter check

- src/pages/JobCalendar.page
Improved color contrast for better accessibility.
> Updates for WCAG color contrast

- src/pages/JobCalendar.page
This is our Feature 246 Branch
> 246 Release Branch

- src/classes/UTIL_HtmlOutput_CTRL.cls
- src/classes/UTIL_HtmlOutput_TEST.cls
> Remove unallowed attributes from url.

- .github/CODEOWNERS
> Make CODEOWNERS GUS-Aware

- cumulusci.yml
- src/classes/VOL_CTRL_NewAndEditVRS.cls
- src/objects/Contact.object
> Remove jigsaw fields from Volunteer Find field sets and verify read access for select options

- cumulusci.yml
* Remove jigsaw fields from Volunteer Find field sets and verify read access for select options [[PR538](https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/pull/538)]
> 250 Release Branch
